### ISSUE TITLE
May i get the modules to run this code?

### ISSUE THREAD

**Issue by MINDYEOI** [jixunbo/LightMBN#14]
Hi! Thank you for sharing the code of your paper.
I want to run this code in a virtual environment so if possible, i want to get a 'requirements.txt' file.
Thank you!

**Comment by fubel** [comment]
I have added a `requirements.txt`. It contains all requirements except for `torch` and `torchvision`, which can of course be downloaded from [here](https://pytorch.org/get-started/locally/).
