### ISSUE TITLE
Some cross-domain LightMBN results

### ISSUE THREAD

**Issue by mikel-brostrom** [jixunbo/LightMBN#21]
For those interested:

| model                       | market                     | duke                         | cuhk03_d |
| ----------- | -----------   | -----------                   |  -----------                   |
| lmbn_n_market        | **0.9641 (0.9156)** | 0.4636 (0.2874)        | ----------- |
| lmbn_n_duke           | 0.5995 (0.3131)       | **0.9201 (0.8371)** | ----------- |
| lmbn_n_cuhk03_d   | 0.5567 (0.3215)       | 0.3142 (0.1782)       | ----------- |
| OSNet-IBN_market  | -----------                  | 48.5 (26.7)                | ----------- |
| OSNet-IBN_duke     | 57.7 (26.1)              | -----------                    | ----------- |

rank1 (mAP) result format. Very similar results for OSNet IBN and LMBN_n in terms of cross-domain results.

Btw, I cannot evaluate on CUHK03 due to structure format errors in the dataset provided here: https://github.com/jixunbo/ReIDataset. If you could fix it I am willing to run the missing experiments and post them here.

**Comment by MaratZakirov** [comment]
@mikel-brostrom I can confirm your result lmbn_n_duke on market. It is very strange that ReID model[s] has such a bad cross-domain capabilities.

**Comment by fubel** [comment]
Thanks for providing the results! 

There are some papers on this (e.g., this one here: https://arxiv.org/pdf/2306.11991). There seems to be quite a domain gap between datasets.
