### ISSUE TITLE
Training Multiple Datasets 

### ISSUE THREAD

**Issue by gayatriprasad** [jixunbo/LightMBN#4]
Hello,

I seem to be the only one asking all the questions ;)  Is there any specific way we can train multiple datasets ? 

Thank You

**Comment by jixunbo** [comment]
haha:grin: no worries
for example, if you'd like to train market1501 and dukemtmc, just use the arg '--data_train market1501+dukemtmc'.

**Comment by gayatriprasad** [comment]
Hello. 

Thank you for the reply. 

That doesn't work. I also tried adding market1501+dukemtmc as a 'combination' in the init file but do not change the error. 

-- Sai

**Comment by jixunbo** [comment]
you can check if the file ‘data_v2 — data manager’ line 136 is the same as the current code or show me the error message

**Comment by gayatriprasad** [comment]
Hey, 

The data_v2 — data manager’ line 136 output (sources) is market1501+dukemtmc.  

The error is get is : 

ValueError: Invalid dataset name. Received "market1501+dukemtmc", but expected to be one of ['market1501', 'cuhk03', 'cuhk03_detected', 'cuhk03_labeled', 'cuhk03_splited', 'dukemtmc', 'msmt17', 'viper', 'grid', 'cuhk01', 'ilids', 'sensereid', 'prid', 'cuhk02', 'mot17', 'qtumai-reid']

**Comment by jixunbo** [comment]
the line 136 should be ‘sources = args.data_train.lower().split('+')’

**Comment by gayatriprasad** [comment]
Thank you. It works. Phew ! Would not have been able to figure it out this quickly.
