### ISSUE TITLE
Using attention module and bnneck

### ISSUE THREAD

**Issue by ghost** [jixunbo/LightMBN#6]
Hello,

1) What's your experience with using/adding bnneck for the experiments ?  

2) How to use attention modules performance improvement ? 

--Sai

**Comment by jixunbo** [comment]
1, yes, we also did some experiments for that, but in our network bnneck does not bring observable improvement.
2, I also tried to insert naive SE attention, CAM or PAM between conv_2 and conv_3 layers, but it doesn't appear better. I could be better if you apply suitable attention modules in the right place. But it still needs experiments.

**Comment by gayatriprasad** [comment]
Thank you. Same was the case with bnnneck. It has not shown any improvement.

**Comment by jixunbo** [comment]
Closed.
