### ISSUE TITLE
This code is missing files

### ISSUE THREAD

**Issue by Mr-Da-Yang** [jixunbo/LightMBN#8]
Hello , First of all thank you very much for your outstanding contribution，but the code you uploaded currently runs missing a few files
1. from loss import make_loss
there is no make_loss.py
2. from prefetch_generator import BackgroundGenerator
there is no prefetch_generator.py

**Comment by jixunbo** [comment]
Hello,
1. the make_loss function is in loss/__init__.py. Please make sure all files downloaded and imported.
2. prefetch_generation is a package installed by 'pip install prefetch_generator'.
Cheers

**Comment by Mr-Da-Yang** [comment]
Thank you very much for your answers, the problem has been solved, and the code has run normally

**Comment by jixunbo** [comment]
Solved.
