### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by mumuner** [jixunbo/LightMBN#9]
Hi, I wanna  inplement your model, but I face a problem: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1LaG1EJpHrxdAxKnSCJ_i0u-nbxSAeiFY (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4a5079d790>: Failed to establish a new connection: [Errno 110] Connection timed out'))
Since this happends because I can download the pretrained model, can you help me to figure it out? please.

**Comment by jixunbo** [comment]
hi, where happens the error, in which step/file?

**Comment by mumuner** [comment]
Hi,
The error happends when I run the osnet.py，I can't loading the .pth file from the drive.goole url. Thank you for your replay!








------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月27日(星期二) 晚上9:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jixunbo/LightMBN] requests.exceptions.ConnectionError (#9)





 
hi, where happens the error, in which step/file?

**Comment by jixunbo** [comment]
ok, then you should find out a way to access google drive and download the pre-trained model of OSNet...
After that configure the path of pre-trained models in osnet.py so as not to download again.
You can find the pre-trained models here https://kaiyangzhou.github.io/deep-person-reid/MODEL_ZOO .
